config/routes.rb
Rails.application.routes.draw do
  rutarel = ENV.fetch('RUTA_RELATIVA', 'minmsip/')
  scope rutarel do
    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'
      if (Rails.configuration.relative_url_root != '/')
        ruta = File.join(Rails.configuration.relative_url_root,
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
    end

    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit',
        :as => 'editar_registro_usuario'
      put 'usuarios/:id' => 'devise/registrations#update',
        :as => 'registro_usuario'
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' }

    root 'msip/hogar#index'
  end  # scope
  mount Msip::Engine, at: rutarel, as: 'msip'
end

app/models/ability.rb
class Ability  < Msip::Ability


  # Se definen habilidades con cancancan
  # @usuario Usuario que hace petición
  def initialize(usuario = nil)
    # El primer argumento para can es la acción a la que se da permiso,
    # el segundo es el recurso sobre el que puede realizar la acción,
    # el tercero opcional es un diccionario de condiciones para filtrar
    # más (e.g :publicado => true).
    #
    # El primer argumento puede ser :manage para indicar toda acción,
    # o grupos de acciones como :read (incluye :show e :index),
    # :create, :update y :destroy.
    #
    # Si como segundo argumento usa :all se aplica a todo recurso,
    # o puede ser una clase.
    #
    # Detalles en el wiki de cancan:
    #   https://github.com/ryanb/cancan/wiki/Defining-Abilities

    # Sin autenticación puede consultarse información geográfica
    can :read, [Msip::Pais, Msip::Departamento, Msip::Municipio, Msip::Clase]
    # No se autorizan usuarios con fecha de deshabilitación
    if !usuario || usuario.fechadeshabilitacion
      return
    end
    can :contar, Msip::Ubicacion
    can :buscar, Msip::Ubicacion
    can :lista, Msip::Ubicacion
    can :descarga_anexo, Msip::Anexo
    can :nuevo, Msip::Ubicacion
    if usuario && usuario.rol then
      case usuario.rol
      when Ability::ROLANALI
        can :read, Msip::Orgsocial
        can :read, Msip::Persona
        can :read, Msip::Ubicacion
        can :new, Msip::Ubicacion
        can [:update, :create, :destroy], Msip::Ubicacion
      when Ability::ROLADMIN
        can :manage, Msip::Orgsocial
        can :manage, Msip::Persona
        can :manage, Msip::Respaldo7z
        can :manage, Msip::Ubicacion
        can :manage, ::Usuario
        can :manage, :tablasbasicas
        self.tablasbasicas.each do |t|
          c = Ability.tb_clase(t)
          can :manage, c
        end
      end
    end
  end # def initialize

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/usuario.rb
require "msip/concerns/models/usuario"
class Usuario < ActiveRecord::Base
  include Msip::Concerns::Models::Usuario
end

app/controllers/application_controller.rb
class ApplicationController < Msip::ApplicationController
  # Previente ataques CSRF elevando una excepción
  # En el caso de APIs, en cambio puedes querer usar :null_session
  protect_from_forgery with: :exception
end

app/controllers/usuarios_controller.rb
require "msip/concerns/controllers/usuarios_controller"

class UsuariosController < Msip::ModelosController
  include Msip::Concerns::Controllers::UsuariosController

  def index
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Msip::BootstrapHelper
end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
  <%= Msip.titulo %>
<% end %>
  
<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <%= opcion_menu "Organizaciones sociales", msip.orgsociales_path %>
      <%= opcion_menu "Personas", msip.personas_path %>
    <% end %>
  <% end %>
  <%= grupo_menus :empuja => :derecha do %>
    <%= opcion_menu "Documentacion", "https://gitlab.com/pasosdeJesus/msip/tree/main/doc/README.md" %>
    <% if current_usuario %>
      <%= despliega_abajo "Administrar" do %>
        <%= opcion_menu "Clave", main_app.editar_registro_usuario_path, desplegable: true %>
        <%= opcion_menu "Copia de respaldo cifrada", msip.respaldo7z_path, desplegable: true %>
        <%= opcion_menu "Usuarios", main_app.usuarios_path, desplegable: true %>
        <%= opcion_menu "Tablas Básicas", msip.tablasbasicas_path, desplegable: true %>
        <%= opcion_menu "Ayuda CA", msip.ayuda_controldeacceso_path, desplegable: true %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", main_app.sign_out_path %>
    <% else %>
      <%= opcion_menu "Acerca de", msip.acercade_path %>
      <%= opcion_menu "Iniciar Sesión", main_app.new_usuario_session_path %>
    <% end %>
  <% end %>
<% end %>
  
<% content_for :piedepagina do %>
  <p><span class='derechos'><a href="https://www.pasosdejesus.org/dominio_publico_colombia.html">Dominio Público de acuerdo a Legislación Colombiana</a><br/>
    Desarrollado por <a href="https://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. 2023.
  </span></p>
<% end %>
  
<%= render template: "layouts/msip/application" %>